name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: build/libs/attendance-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/app/attendance-0.0.1-SNAPSHOT.jar
          overwrite: true 


      - name: Run JAR on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            pkill -f 'java -jar' || true
            sh -c 'nohup java -jar /home/ubuntu/app/attendance-0.0.1-SNAPSHOT.jar > /home/ubuntu/app/log.txt 2>&1 &'
